
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 15
#define YY_END_OF_BUFFER 16
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[375] =
    {   0,
        0,    0,   16,   15,    1,    3,    2,    7,    7,    7,
        8,    9,    6,    6,    8,    6,    7,    6,   11,    7,
        5,    5,    5,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,    7,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,    1,    2,    0,
       13,    0,   13,    0,    0,    0,    5,   10,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   11,    0,    7,   14,   14,
       14,   14,   14,   14,    4,   14,   14,   14,   14,    4,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   14,    4,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   11,    0,
       11,   14,   14,   14,   14,   14,   14,   14,    4,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,    4,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,    0,    0,    0,    0,    0,    0,    0,    0,   10,

        0,   10,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   14,   14,   14,   14,   14,    4,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,    4,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,    0,    0,    0,    0,
        0,   12,    0,    0,    0,    0,    0,    0,    0,    0,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,    0,    0,    0,    0,
        0,    0,    4,    0,   14,   14,   14,   14,   14,   14,

       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,    0,    0,
        0,   14,   14,   14,    0,   14,   14,   14,   14,   14,
       14,   14,    0,   14,   14,   14,   14,   14,   14,    0,
       14,   14,   14,   14,   14,    0,   14,   14,   14,    0,
        0,   14,    0,    0,   14,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   35,   35,
       35,   35,   49,   35,   50,   35,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   35,   35,   60,   61,   62,
       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       35,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3
    } ;

static yyconst flex_int16_t yy_base[379] =
    {   0,
        0,    0,  846,  847,   71,  847,    0,  839,  847,  834,
       72,  847,  830,  847,  847,  823,   66,  818,   60,  820,
      816,  815,  814,  786,   61,   69,   45,   35,   93,   77,
       94,   56,   68,   49,   99,  785,   87,   83,   91,   85,
      105,   97,  106,  109,   89,   90,  112,  167,    0,  828,
      827,  822,  821,  171,  811,  189,  847,  159,  791,  787,
      801,  135,  138,  144,  784,  783,  762,  758,  771,  126,
      129,  122,  755,  754,  800,  182,  191,  847,  768,  767,
      159,  166,  165,  183,  172,  178,  196,  146,  148,  766,
      189,   34,  188,  195,  190,  214,  205,  207,  211,  201,

      192,  199,  206,  208,  209,  210,  212,  213,  220,  215,
      221,  223,  224,  225,  233,  236,  238,  243,  244,  302,
      293,  297,  796,  286,  795,  293,  784,  293,  776,  794,
      793,  792,  791,  294,  763,  789,  760,  750,  259,  743,
      785,  784,  783,  782,  263,  730,  780,  727,  295,  776,
      775,  284,  273,  287,  294,  292,  291,  296,  311,  303,
      302,  304,  318,  321,  325,  320,  327,  333,  322,  328,
      329,  313,  324,  330,  331,  332,  334,  338,  326,  339,
       59,  341,  342,  345,  352,  346,  348,  356,  359,  350,
      361,  774,  399,  415,  773,  433,  424,  772,  425,  417,

      771,  770,  771,  770,  743,  739,  767,  753,  765,  764,
      713,  709,  761,  722,  388,  405,  398,  382,  406,  399,
      420,  416,  423,  427,  433,  430,  425,  380,  442,  434,
      435,  440,  443,  441,  445,  447,  446,  449,  451,  454,
      459,  457,  458,  463,  464,  465,  517,  757,  520,  581,
      521,  847,  756,  524,  744,  756,  754,  713,  748,  745,
      500,  501,  503,  491,  512,  499,  510,  517,  518,  526,
      524,  529,  511,  513,  509,  519,  520,  525,  534,  527,
      538,  539,  545,  542,  551,  549,  742,  589,  602,  741,
      605,  742,  847,  741,  569,  575,  577,  523,  608,  587,

      531,  426,  580,  584,  583,  594,  579,  589,  590,  591,
      638,  599,  595,  598,  603,  601,  605,  609,  666,  738,
      670,  630,  633,  634,  716,  637,  621,  649,  647,  636,
      642,  640,  691,  643,  644,  651,  652,  658,  660,  712,
      700,  672,  675,  666,  665,  687,  713,  668,  673,  722,
      713,  689,  694,  686,  674,  719,  707,  692,  681,  709,
      704,  682,  678,  695,  707,  669,  678,  696,  669,  687,
      453,  385,  271,  847,  763,  766,  769,  281
    } ;

static yyconst flex_int16_t yy_def[379] =
    {   0,
      374,    1,  374,  374,  374,  374,  375,  376,  374,  377,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  374,  375,  376,
      376,  377,  377,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  374,  374,  374,  374,
      374,  374,  374,  374,  378,  378,  378,  378,  378,  378,

      378,  378,  378,  378,  378,  378,  378,  378,  378,  378,
      378,  378,  378,  378,  378,  378,  378,  378,  374,  374,
      374,  378,  378,  378,  374,  378,  378,  378,  378,  378,
      378,  378,  374,  378,  378,  378,  378,  378,  378,  374,
      378,  378,  378,  378,  378,  374,  378,  378,  378,  374,
      374,  378,  374,  374,  378,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,    0,  374,  374,  374,  374
    } ;

static yyconst flex_int16_t yy_nxt[920] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,    9,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
        9,   21,   22,   23,    9,   24,   24,   25,   26,   27,
       28,   24,   24,   29,   24,   30,   24,   24,   24,   31,
       24,   32,   33,   34,   24,   24,   35,   24,   36,   36,
       24,   24,   37,   38,   39,   40,   24,   24,   41,   42,
       24,   24,   24,   43,   24,   44,   45,   46,   24,   24,
       47,   24,   48,   54,   48,   54,   75,  163,   76,   89,
       86,   99,   87,   80,   80,   97,   81,   55,   77,   77,
       56,   59,   88,   82,   80,   60,   61,   62,   80,   83,

       77,   63,   84,   64,   65,   80,   93,   85,   80,   66,
       80,  238,   98,   77,   77,   94,   67,   80,   80,   95,
       68,   69,   70,   90,   77,   71,   80,   72,   73,   91,
       92,  100,   80,   74,   80,   96,   80,  101,   80,   80,
       80,  104,   80,   80,  102,  105,   80,  118,   80,  103,
      106,  112,  107,  109,   80,   80,  114,  117,   80,  113,
       90,   80,  108,  116,  130,  110,  111,  132,   48,  119,
       48,  115,   54,  134,   54,  125,  145,   58,  131,  160,
      141,  133,  135,  143,  146,  161,   55,  126,  126,   56,
      121,  153,  121,  142,  152,   80,  144,   80,   75,  126,

       76,  154,  155,  122,  150,  123,  150,   56,   80,  151,
       77,   77,  126,  126,   80,   80,  157,  124,  124,  156,
      158,   80,   77,  126,  159,   90,  164,   80,  162,  124,
      168,  165,   80,  169,  171,   77,   77,   80,   80,   80,
      170,   80,  124,  124,   80,   80,   77,  166,   80,  173,
       80,  172,  167,  124,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,  179,  174,  175,  176,   80,
       80,  180,   80,   80,   80,   57,  178,  177,  182,   57,
      184,  181,   80,   79,   90,   80,  188,   80,  183,  189,
      185,  186,   80,   80,  121,  187,  121,  190,  194,  198,

      194,  198,  191,  121,  199,  121,  201,  122,  201,   57,
       57,  202,  195,  149,  215,  196,  122,  219,  192,   90,
      120,  218,   80,   77,   77,  220,  216,  212,  210,  222,
      193,  193,  293,   80,  206,   77,   80,  217,  204,  223,
       80,   80,  193,   80,  221,   80,   90,  224,   77,   77,
      226,   80,   80,   80,  225,  193,  193,  227,  228,   77,
       80,   90,   80,  229,  230,   90,  193,   80,   90,   80,
       80,   80,   90,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,  237,  235,  234,   80,   80,  231,
       80,   80,  236,  232,   80,   80,  240,   80,  233,   80,

      239,   80,  242,  241,  244,   80,   90,  243,   80,   90,
       80,   90,  248,  261,  248,   90,  194,  249,  194,  264,
      246,  272,  293,  263,  245,  121,  121,  121,  121,   80,
      195,   80,  266,  196,  251,  200,  251,   80,  122,  122,
      262,  265,  197,  199,  252,  126,  126,   80,   80,  253,
       90,  196,  124,  124,   80,   80,  268,  126,  269,  267,
      270,  254,  254,   90,  124,   80,  271,   90,   90,   80,
      126,  126,   80,  254,   80,   80,   80,  124,  124,   80,
      273,  126,   80,   80,   80,  274,  254,  254,  124,   80,
       80,   80,   80,  276,   80,   80,   80,  254,   80,  275,

       80,   90,  277,   80,  278,  279,   80,   80,   80,  281,
      282,  283,   80,   80,   80,  373,  280,  284,  121,   90,
      121,  121,  251,  121,  251,   90,  286,  295,  285,   90,
      296,  122,  252,  298,  122,  247,  297,  290,  249,  290,
       80,  299,  291,  300,  301,  193,  193,  302,   80,   80,
       80,  303,   80,  304,  305,  306,  324,  193,   80,   80,
       80,   80,   80,  308,  327,  307,   80,   80,   80,   80,
      193,  193,   80,   80,   80,   80,   80,  309,   80,  311,
       80,  193,  251,   80,  251,  312,  310,   80,   80,   90,
      313,   80,  252,  314,   80,  315,  316,  287,   80,  250,

       80,  317,  320,  251,  320,  251,  251,  321,  251,  288,
      288,  325,  322,  252,  323,   90,  252,  318,   80,   90,
      289,  288,   90,  291,   80,  326,   80,  328,   80,   80,
      254,  254,   80,   80,  288,  288,   80,  329,   80,   80,
       80,  333,  254,   80,   80,  288,  330,   80,   80,  332,
       80,  331,   80,  335,   80,  254,  254,   80,   80,  338,
       90,  334,   90,   90,  341,   90,  254,  251,  336,  251,
       80,  251,  339,  251,   90,   90,  337,  252,  342,   80,
      343,  252,   80,   80,  319,   80,   80,   80,  321,   80,
      344,   80,   80,   80,  288,  288,   80,   90,   80,   90,

       80,   80,  345,  351,   90,  348,  288,   80,   90,   80,
      349,  347,  352,   90,   80,   80,  354,   80,   90,  288,
      288,   80,   80,   80,   80,  372,   90,  371,   90,  370,
      288,   90,  293,   90,  355,  369,  293,  368,   80,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,   80,
      357,  356,  353,  350,  346,  340,  321,  293,  293,  291,
      319,  293,   80,   49,   57,   49,   50,  294,   50,   52,
      293,   52,   57,  292,  289,  249,  260,   57,  259,  258,
       57,   57,  257,   57,  256,  255,   57,   57,  202,  202,
      199,  250,  247,  151,  151,  214,   57,  213,   57,   57,

       57,   57,  211,  209,  208,   57,  207,   57,   57,   57,
       57,  205,  203,  200,  197,   80,   80,   80,  149,  148,
      147,  140,  139,  138,  137,  136,  129,  128,  127,  120,
       53,   53,   51,   51,   80,   80,   57,   57,   57,   78,
       57,   58,   57,   53,   51,  374,    3,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static yyconst flex_int16_t yy_chk[920] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,   11,    5,   11,   19,   92,   19,   28,
       27,   34,   27,   92,   28,   32,   25,   11,   19,   19,
       11,   17,   27,   25,   27,   17,   17,   17,   34,   25,

       19,   17,   26,   17,   17,   32,   30,   26,  181,   17,
       25,  181,   33,   19,   19,   30,   17,   33,   26,   31,
       17,   17,   17,   29,   19,   17,   30,   17,   17,   29,
       29,   35,   38,   17,   40,   31,   37,   37,   45,   46,
       39,   38,   29,   31,   37,   38,   42,   46,   35,   37,
       39,   42,   39,   40,   41,   43,   43,   45,   44,   42,
       41,   47,   39,   44,   62,   41,   41,   63,   48,   47,
       48,   43,   54,   64,   54,   58,   72,   58,   62,   88,
       70,   63,   64,   71,   72,   89,   54,   58,   58,   54,
       56,   82,   56,   70,   81,   88,   71,   89,   76,   58,

       76,   83,   83,   56,   77,   56,   77,   56,   81,   77,
       76,   76,   58,   58,   83,   82,   85,   56,   56,   84,
       86,   85,   76,   58,   87,   93,   94,   86,   91,   56,
       97,   95,   84,   98,  100,   76,   76,   93,   91,   95,
       99,  101,   56,   56,   94,   87,   76,   96,  102,  102,
      100,  101,   96,   56,   97,  103,   98,  104,  105,  106,
       99,  107,  108,   96,  110,  107,  103,  103,  104,  109,
      111,  108,  112,  113,  114,  139,  106,  105,  110,  145,
      113,  109,  115,  378,  112,  116,  116,  117,  111,  117,
      114,  115,  118,  119,  121,  115,  121,  118,  122,  124,

      122,  124,  119,  120,  124,  120,  126,  121,  126,  128,
      134,  126,  122,  149,  153,  122,  120,  157,  120,  152,
      120,  156,  153,  149,  149,  158,  154,  145,  139,  161,
      120,  120,  373,  152,  134,  149,  154,  155,  128,  162,
      157,  156,  120,  155,  159,  158,  160,  163,  149,  149,
      165,  161,  160,  162,  164,  120,  120,  166,  167,  149,
      159,  168,  172,  169,  171,  170,  120,  163,  168,  166,
      164,  169,  172,  173,  165,  179,  167,  170,  171,  174,
      175,  176,  168,  177,  179,  177,  176,  178,  180,  173,
      182,  183,  178,  174,  184,  186,  183,  187,  175,  190,

      182,  185,  185,  184,  187,  188,  180,  186,  189,  188,
      191,  190,  193,  215,  193,  188,  194,  193,  194,  218,
      191,  228,  372,  217,  189,  197,  199,  197,  199,  228,
      194,  218,  220,  194,  196,  200,  196,  215,  197,  199,
      216,  219,  197,  199,  196,  200,  200,  217,  220,  196,
      221,  196,  197,  197,  216,  219,  223,  200,  224,  222,
      225,  196,  196,  230,  197,  222,  226,  302,  227,  221,
      200,  200,  223,  196,  227,  302,  224,  197,  197,  226,
      229,  200,  225,  230,  231,  231,  196,  196,  197,  232,
      234,  229,  233,  233,  235,  237,  236,  196,  238,  232,

      239,  237,  234,  240,  235,  236,  242,  243,  241,  239,
      240,  241,  244,  245,  246,  371,  238,  242,  247,  246,
      247,  249,  251,  249,  251,  243,  245,  261,  244,  266,
      262,  247,  251,  264,  249,  247,  263,  254,  249,  254,
      264,  265,  254,  267,  268,  247,  247,  269,  266,  261,
      262,  270,  263,  271,  272,  273,  298,  247,  275,  267,
      273,  265,  274,  275,  301,  274,  268,  269,  276,  277,
      247,  247,  298,  271,  278,  270,  280,  276,  272,  278,
      301,  247,  250,  279,  250,  280,  277,  281,  282,  279,
      281,  284,  250,  282,  283,  283,  284,  250,  286,  250,

      285,  285,  288,  289,  288,  289,  291,  288,  291,  250,
      250,  299,  295,  289,  297,  303,  291,  286,  295,  305,
      289,  250,  296,  291,  296,  300,  297,  304,  307,  303,
      289,  289,  305,  304,  250,  250,  300,  306,  308,  309,
      310,  311,  289,  306,  313,  250,  307,  314,  312,  310,
      316,  309,  315,  313,  317,  289,  289,  299,  318,  322,
      308,  312,  315,  314,  327,  317,  289,  319,  316,  319,
      327,  321,  324,  321,  326,  323,  318,  319,  328,  322,
      329,  321,  323,  324,  319,  330,  326,  311,  321,  332,
      330,  331,  334,  335,  319,  319,  329,  339,  328,  338,

      336,  337,  332,  341,  334,  336,  319,  338,  331,  339,
      337,  335,  343,  342,  345,  344,  347,  348,  352,  319,
      319,  342,  349,  355,  343,  370,  345,  369,  355,  368,
      319,  344,  367,  348,  349,  366,  365,  364,  352,  363,
      362,  361,  360,  359,  358,  357,  356,  354,  353,  341,
      351,  350,  346,  340,  333,  325,  320,  294,  292,  290,
      287,  260,  347,  375,  259,  375,  376,  258,  376,  377,
      257,  377,  256,  255,  253,  248,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  204,  203,  202,  201,
      198,  195,  192,  151,  150,  148,  147,  146,  144,  143,

      142,  141,  140,  138,  137,  136,  135,  133,  132,  131,
      130,  129,  127,  125,  123,   90,   80,   79,   75,   74,
       73,   69,   68,   67,   66,   65,   61,   60,   59,   55,
       53,   52,   51,   50,   36,   24,   23,   22,   21,   20,
       18,   16,   13,   10,    8,    3,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,

      374,  374,  374,  374,  374,  374,  374,  374,  374,  374,
      374,  374,  374,  374,  374,  374,  374,  374,  374
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pravila.lex"
#line 2 "pravila.lex"
	#include <ctype.h>
	#include <string.h>
	
	int ocekuj_negativni=0, bio_iden=0, br_linije=1;
	
	/* deklaracija tablice ključnih riječi, operatora i specijalnih znakova */
	char* kros[]={"program", "implicit none", "integer", "real", "double precision", "complex", "character", "len", "logical", "parameter", "dimension", ".true.", ".false.", "if", "then", "elseif", "else", "endif", "do", "while", "exit", "print", "read", "end", "call", "contains", "subroutine", "function", "+", "-", "*", "/", "**", "<", ">", "==", "=", "/=", "<=", ">=", ".lt.", ".gt.", ".eq.", ".ne.", ".le.", ".ge.", ".not.", ".and.", ".or.", ".eqv.", ".neqv.", "_", ":", ";", "::", "?", "$", "&", "%", "'", ".", ",", "(", ")", "\""};
	
	/* deklaracija tablice uniformnih znakova */
	char *tuz_uz;		/* stupac s uniformnim znakovima */
	int *tuz_p;		/* stupac s "pokazivačima" */
	int *tuz_bl;		/* stupac s brojevima linija */
	int tuz_cnt = 0;	/* brojač redaka */
				/* (definicije u mainu) */
	
	/* deklaracija tablice identifikatora */
	char **tidn;		/* stupac s imenima identifikatora */
	int tidn_cnt = 0;	/* brojač redaka */
				/* (definicija u mainu) */
	
	/* deklaracija tablice konstanti */
	char **tkon_val;	/* stupac s vrijednostima */
	char *tkon_tip;		/* stupac s tipovima konstanti */
	int tkon_cnt = 0;	/* brojac redaka */
				/* (definicije u mainu) */
	
	
	
	
	/* ----- POMOĆNE FUNKCIJE -----*/
	
	int makni_bjeline(char* mojtext){
		int i, j;
		
		for(i=0; mojtext[i] != '\0'; i++){
			if (mojtext[i] == ' ' || mojtext[i] == '\t'){
			
				/* micanje niza za 1 ulijevo */
				for(j=i; mojtext[j] != '\0'; j++)
					mojtext[j] = mojtext[j+1];
				
				i--;	/* za slučaj dvostrukih bjelina */
			}
		}
		
		return i;
	}
	
	void greska(char spec, char *poruka, char* mojtext){
		if(spec=='G')
			fprintf(stderr, "GREŠKA: ");
		else if(spec=='U')
			fprintf(stderr, "upozorenje: ");

		fprintf(stderr, "linija %d: %s \n\t\"\"\"%s\"\"\"\n", br_linije, poruka, mojtext);
	}



	int is_real(char* mojtext){	/* provjerava je li broj tipa real i usput smanjuje E, D i Q */
		int i, real=0;
		
		for(i=0; mojtext[i] != '\0'; i++){
			if (mojtext[i]=='E' || mojtext[i]=='D' || mojtext[i]=='Q' ||
			    mojtext[i]=='e' || mojtext[i]=='d' || mojtext[i]=='q' || mojtext[i]=='.'){
				mojtext[i] = tolower(mojtext[i]);
				real=1;
			}
		}
		return real;
	}
	
	
	
	
	/* ----- FUNKCIJE ZA UPRAVLJANJE TABLICAMA ----- */
	
	void dodaj_tuz(char uz, int i, char* mojtext){
		tuz_uz = (char*) realloc (tuz_uz, (tuz_cnt+1)*sizeof(char));
		tuz_uz[tuz_cnt] = uz;
		
		tuz_p = (int*) realloc (tuz_p, (tuz_cnt+1)*sizeof(int));
		tuz_p[tuz_cnt] = i;
		
		tuz_bl = (int*) realloc (tuz_bl, (tuz_cnt+1)*sizeof(int));
		tuz_bl[tuz_cnt] = br_linije;
		
		tuz_cnt++;
	}
	
	void dodaj_tidn(){	/* argumenti su uvijek yytext i yyleng */
		tidn = (char**) realloc (tidn, (tidn_cnt+1)*sizeof(char*));
		tidn[tidn_cnt] = (char*) malloc((yyleng+1)*sizeof(char));
		strcpy(tidn[tidn_cnt], yytext);

		tidn_cnt++;
	}
	
	void dodaj_tkon(char* mojtext, int duljina, char tip){
		tkon_val = (char**) realloc (tkon_val, (tkon_cnt+1)*sizeof(char*));
		tkon_val[tkon_cnt] = (char*) malloc((duljina+1)*sizeof(char));
		strcpy(tkon_val[tkon_cnt], mojtext);
		
		tkon_tip = (char*) realloc (tkon_tip, (tkon_cnt+1)*sizeof(char));
		tkon_tip[tkon_cnt] = tip;

		tkon_cnt++;
	}
	
	int trazi_tkon(char* mojtext, int duljina, char tip){
		/* Vraća indeks tablice konstanti u kojoj je tražena konstanta.
		   Ako konstanta nije nađena, dodaje ju i vraća njegn indeks. */
		   
		int i;
		
		/* pretraga tablice konstanti */
		for (i=0; i<tkon_cnt; i++){
			if (strcmp(mojtext, tkon_val[i]) == 0 && tkon_tip[i] == tip) /* ako su jednaki... */
				return i;
		}
		
		/* ako nije nađeno */
		dodaj_tkon(mojtext, duljina, tip);
		
		return tkon_cnt-1;
	}
	
	
	
	
	
	/* ----- FUNKCIJE ZA UPRAVLJANJE DOBIVENIM IZRAZIMA ----- */	
	
	
	/* funkcija za upravljanje identifikatorima */
	void fidn(){
		int i, nadjeno=0;
		
		if(yyleng>254)
			greska('G', "Varijabla smije imati najviše 254 znaka!", yytext);
		
		else{
			/* pretraga tablice identifikatora */
			for (i=0; i<tidn_cnt; i++){
	
				if (strcmp(yytext, tidn[i]) == 0){ /* ako su jednaki... */
					dodaj_tuz('I', i, yytext);
					nadjeno=1;
					break;
				}
			}
	
			if (nadjeno==0){
				dodaj_tuz('I', tidn_cnt, yytext);
				dodaj_tidn();
			}
		}
	
		ocekuj_negativni=0;
		bio_iden=1;
	}


	/* funkcija za upravljanje ključnim riječima, operatorima i specijalnim znakovima */	
	void fkros(){
		int i=0, nadjeno=0;
		char mojtext[17];
		
		/* pretvorba izraza u "lowercase" */
		do{
			mojtext[i] = tolower(yytext[i]);
			i++;
		}while(yytext[i-1]!=0);
		
		
		/* pretraga KROS tablice */
		for (i=0; i<(sizeof(kros)/sizeof(char*)); i++){
		
			if (strcmp(mojtext, kros[i]) == 0){ /* ako su jednaki... */
				
				dodaj_tuz('K', i, mojtext);
				
				nadjeno=1;
				break;
			}
		}
		
		if (nadjeno==0){ /* ako ta kodna riječ nekim čudom nije nađena... */
			greska('U', "Kodna riječ nije nađena u KROS tablici pa se smatra identifikatorom.", yytext);
			fidn();
		}
	}


	/* funkcija za upravljanje konstantama */
	void fkonst(char spec){
		int i=0, nadjeno=0, tkonindeks, duljina;
		char mojtext[17], broj[32];
			
		
		/* broj s minusom na početku */
		if(spec == 'n'){
			
			char r = is_real(yytext) ? 'R' : 'I';	/* r postaje R ako je broj tipa real, a I ako je tipa integer */
			
			if(ocekuj_negativni){
				/* radi se o negativnom broju, a ne o operaciji oduzimanja + pozitivan broj. */
				tkonindeks = trazi_tkon(yytext, yyleng, r);
				dodaj_tuz('C', tkonindeks, yytext);
			}
			else{  /* znak minus, pa pozitivan broj */
				
				/* prepisivanje yytexta bez prvog znaka (koji je '-') */
				i=1;
				do{	
					mojtext[i] = yytext[i];	
					i++;
				}while(yytext[i-1]!=0);
				
				/* procesiranje znaka minus */
				yytext[0] = '-'; yytext[1]=0;
				fkros();
				ocekuj_negativni=0;
				
				/* procesiranje pozitivnog broja */
				tkonindeks = trazi_tkon(mojtext, yyleng-1, r);
				dodaj_tuz('C', tkonindeks, mojtext);
			}
			
		}
		
		/* broj bez minusa na početku */
		else if(spec == 'p'){
			
			char r = is_real(yytext) ? 'R' : 'I';	/* r postaje R ako je broj tipa real, a I ako je tipa integer */
			
			tkonindeks = trazi_tkon(yytext, yyleng, r);
			dodaj_tuz('C', tkonindeks, yytext);
		}
		
		/* kompleksni broj */
		else if(spec == 'c'){
			
			/* prepisivanje yytexta */
			do{	
				mojtext[i] = yytext[i];
				i++;
			}while(yytext[i-1]!=0);
			
			duljina = makni_bjeline(mojtext);
			
			if(bio_iden){ /* prije kompleksnog broja je bio identifikator, dakle ovo su zapravo parametri funkcije */
				
				/* procesiranje otvorene zagrade */
				yytext[0] = '('; yytext[1]=0;
				fkros();
				ocekuj_negativni=0;
				
				
				/* izdvajanje i procesiranje prvog broja */
				for(i=1; mojtext[i] != ','; i++)
					broj[i-1] = mojtext[i];
				broj[i-1] = '\0';
				duljina = i-1;
				
				char r = is_real(mojtext) ? 'R' : 'I';	/* r postaje R ako je broj tipa real, a I ako je tipa integer */
				tkonindeks = trazi_tkon(broj, duljina, r);
				dodaj_tuz('C', tkonindeks, broj);
				
				
				/* procesiranje zareza */
				yytext[0] = ','; yytext[1]=0;
				fkros();
				ocekuj_negativni=0;
				
				
				/* izdvajanje i procesiranje drugog broja */
				for(i++; mojtext[i] != ')'; i++)
					broj[i-duljina-2] = mojtext[i];
				broj[i-duljina-2] = '\0';
				duljina = i-2 - duljina;
				
				r = is_real(mojtext) ? 'R' : 'I';	/* r postaje R ako je broj tipa real, a I ako je tipa integer */
				tkonindeks = trazi_tkon(broj, duljina, r);
				dodaj_tuz('C', tkonindeks, broj);
				
				
				/* procesiranje zatvorene zagrade */
				yytext[0] = ')'; yytext[1]=0;
				fkros();
				ocekuj_negativni=0;				
				
			}
			else { /* ovo zaista jest kompleksni broj */
				is_real(mojtext);	/* samo da se smanje E, D i Q u e, d i q */
				tkonindeks = trazi_tkon(mojtext, duljina, 'C');
				dodaj_tuz('C', tkonindeks, mojtext);
			}
		}
		
		/* string */
		else if(spec == 's'){
			tkonindeks = trazi_tkon(yytext, yyleng, 'S');
			dodaj_tuz('C', tkonindeks, yytext);
		}
		
		
		ocekuj_negativni=0;
		bio_iden=0;
	}
	



	int main(){
	
		tuz_uz = (char*) malloc(1*sizeof(char));	/* stupac s uniformnim znakovima */
		tuz_p = (int*) malloc(1*sizeof(int));		/* stupac s "pokazivačima" */
		tuz_bl = (int*) malloc(1*sizeof(int));		/* stupac s brojevima linija */
		
		tidn = (char**) malloc(1*sizeof(char*));	/* niz pokazivača na stringove */
		
		tkon_val = (char**) malloc(1*sizeof(char*));	/* stupac s vrijednostima */
		tkon_tip = (char*) malloc(1*sizeof(char));	/* stupac s tipovima konstanti */
		
		FILE *filetuz, *filekros, *fileiden, *filekon;	/* izlazne datoteke */
		
		int i;
		char *temp, *temp2;
		
		
		
		yylex();
		
		
		/* ISPIS TABLICA U DATOTEKE */
		
		filetuz = fopen("1-uniformni-znakovi.txt", "w");
		fprintf(filetuz, "       uniformni          linija         izraz\n");
		fprintf(filetuz, "indeks   znak    kazaljka  koda         iz koda\n");
		fprintf(filetuz, "---------------------------------------------------------\n");
		for(i=0; i<tuz_cnt; i++){
			if (tuz_uz[i] == 'K'){
				temp = "KROS";
				temp2 = kros[tuz_p[i]];
			}
			if (tuz_uz[i] == 'I'){
				temp = "IDN";
				temp2 = tidn[tuz_p[i]];
			}
			if (tuz_uz[i] == 'C'){
				temp = "KON";
				temp2 = tkon_val[tuz_p[i]];
			}
			fprintf(filetuz, "%d\t%s\t   %d\t   %d\t\t%s\n", i, temp, tuz_p[i], tuz_bl[i], temp2);
		}
		fprintf(filetuz, "---------------------------------------------------------\n");
		fclose(filetuz);
		
		
		filekros = fopen("2-kros.txt", "w");
		fprintf(filekros, "\tključna riječ, operator,\nindeks\t  ili specijalni znak\n");
		fprintf(filekros, "--------------------------------\n");
		for(i=0; i<sizeof(kros)/sizeof(char*); i++)
			fprintf(filekros, "%d\t    %s\n", i, kros[i]);
		fprintf(filekros, "--------------------------------\n");
		fclose(filekros);
		
		
		fileiden = fopen("3-identifikatori.txt", "w");
		fprintf(fileiden, "indeks\tidentifikator\n---------------------\n");
		for(i=0; i<tidn_cnt; i++)
			fprintf(fileiden, "%d\t%s\n", i, tidn[i]);
		fprintf(fileiden, "---------------------\n");
		fclose(fileiden);
		
		
		filekon = fopen("4-konstante.txt", "w");
		fprintf(filekon, "indeks\ttip\t  konstanta\n------------------------------------\n");
		for(i=0; i<tkon_cnt; i++){
			if(tkon_tip[i]=='R') temp = "real";
			if(tkon_tip[i]=='I') temp = "integer";
			if(tkon_tip[i]=='C') temp = "complex";
			if(tkon_tip[i]=='S') temp = "string";
			fprintf(filekon, "%d\t%s\t  %s\n", i, temp, tkon_val[i]);
		}
		fprintf(filekon, "------------------------------------\n");
		fclose(filekon);
		
		
		printf("Program uspješno završen. Izlazne su tablice u datotekama u ovom direktoriju.\n");
		
		
		/* oslobađanje memorije */
		free(tuz_uz);
		free(tuz_p);
		free(tuz_bl);
		
		for(i=0; i<tidn_cnt; i++)
			free(tidn[i]);
			
		for(i=0; i<tkon_cnt; i++)
			free(tkon_val[i]);
		free(tkon_tip);
		
		
		return 0;
	}
	
	
#line 1188 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 434 "pravila.lex"



#line 1374 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 375 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 847 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 437 "pravila.lex"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 438 "pravila.lex"
{ocekuj_negativni=0; bio_iden=0;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 439 "pravila.lex"
{ocekuj_negativni=0; bio_iden=0; br_linije++;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 441 "pravila.lex"
{fkros(); ocekuj_negativni=0; bio_iden=0;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 442 "pravila.lex"
{fkros(); ocekuj_negativni=1; bio_iden=0;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 443 "pravila.lex"
{fkros(); ocekuj_negativni=0; bio_iden=0;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 444 "pravila.lex"
{fkros(); ocekuj_negativni=0; bio_iden=0;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 445 "pravila.lex"
{fkros(); ocekuj_negativni=1; bio_iden=0;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 446 "pravila.lex"
{fkros(); ocekuj_negativni=0; bio_iden=0;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 448 "pravila.lex"
fkonst('n');	/* nakon svake konstante: */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 449 "pravila.lex"
fkonst('p');	/* ocekuj_negativni=0 */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 450 "pravila.lex"
fkonst('c');	/* i bio_iden=0 */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 451 "pravila.lex"
fkonst('s');
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 453 "pravila.lex"
fidn();		/* ocekuj_negativni=0, bio_iden=1 */
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 455 "pravila.lex"
ECHO;
	YY_BREAK
#line 1533 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 375 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 375 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 374);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 455 "pravila.lex"




