/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
static yyconst short int yy_accept[465] =
    {   0,
        0,    0,   87,   85,   83,   84,   83,   85,   85,   79,
       78,   73,   74,   77,   85,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,    0,   82,    0,
        0,    0,   75,    0,   71,   72,   76,   80,    0,    0,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   41,   81,    0,   80,   32,   80,

       12,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   17,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,    7,   40,
       42,    1,   80,   80,   80,   80,   80,   60,   80,   69,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   65,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   57,   80,
       80,   80,   37,   80,   25,   80,   80,   80,   80,   80,

       80,   80,   80,   80,   70,   80,   80,   80,   33,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   36,   19,   80,   24,   80,   80,
       34,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   26,   68,   80,   80,
       80,   80,   80,   80,   80,   80,   11,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   62,   80,   64,   45,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   35,   80,   80,   80,   80,    8,   80,   80,   80,

       80,   80,   80,   22,   80,   39,   80,   80,   61,   80,
        5,   80,   80,   80,   80,    9,   80,   80,   80,   80,
       63,   80,   80,   80,   80,   27,   80,   80,   80,   80,
       80,   80,   43,   80,   80,   80,   80,   80,    3,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       80,   80,    4,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   66,   80,   28,   67,   80,   18,
       14,   80,   80,   80,   80,   80,   80,   80,   21,   80,
       80,   80,   80,   80,   80,   20,   80,   80,   80,   49,
       55,   80,   80,   52,   56,    6,   80,   80,   80,   80,

       80,   80,   15,   80,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   29,   80,
       80,   44,   80,   80,   80,   10,   38,    2,   80,   30,
       80,   80,   80,   80,   80,   31,   80,   80,   53,   13,
       80,   80,   80,   80,   47,   48,   50,   51,   80,   80,
       80,   80,   16,   80,   54,   80,   58,   23,   46,   80,
       80,   80,   59,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    1,    7,    1,
        1,    1,    1,    1,    8,    1,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,    1,   12,
       13,   14,   15,    1,   16,   17,   18,   19,   20,   17,
       21,   17,   22,   17,   17,   23,   17,   17,   24,   17,
       17,   17,   25,   26,   17,   17,   17,   17,   17,   17,
        1,   27,    1,    1,   17,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   17,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
       51,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    3,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3
    } ;

static yyconst short int yy_base[468] =
    {   0,
        0,    0,  490,  491,  491,  491,  491,   46,  462,  474,
      491,   48,  491,  491,  473,    0,   48,   28,   28,   26,
       30,   37,   44,  442,   39,  453,   49,   54,   48,   18,
       55,  452,   61,   43,  443,   57,   56,   92,  491,  479,
       93,   96,  491,  473,  491,  491,  491,    0,   98,  453,
      448,  440,   65,  435,  430,  430,  434,  442,  431,  432,
       73,  440,  437,   76,  422,  420,  434,  437,  423,  421,
       79,  411,  421,  415,  409,  413,  417,  417,  409,  422,
      407,   66,  408,   82,  416,   86,  411,  420,  402,  405,
      410,  409,  413,  405,   86,  491,  434,  397,    0,  399,

      423,  416,  393,  404,  404,  383,  397,  390,  395,  400,
      382,  389,  385,  387,  393,  386,  385,  392,  374,  379,
      381,  371,  373,  382,  369,  111,  369,  116,  381,  384,
      367,  368,  363,  362,  361,  374,  359,  372,  371,  355,
      353,  358,  354,  370,  365,   85,  350,  357,    0,    0,
        0,  491,  362,  347,  346,  351,  354,    0,  353,    0,
      358,  349,  346,  341,  345,  351,  341,  349,  340,  333,
      347,  331,  334,  331,  327,  327,  340,  325,    0,  320,
      329,  336,  337,  338,  315,  324,  331,  332,    0,  315,
      332,  312,    0,  326,  331,  323,  311,  315,  323,  320,

      315,  312,  303,  310,  302,  306,  298,  312,    0,  298,
      314,  295,  307,  310,  298,  305,  304,  299,  298,  301,
      292,  295,  286,  284,    0,    0,  292,    0,  281,  295,
        0,  292,  289,  293,  292,  281,  290,  285,  288,  287,
      276,  285,  278,  267,  266,  267,  259,  273,  272,  279,
      260,  265,  274,  271,  266,  282,    0,    0,  268,  274,
      253,  251,  252,  254,  247,  259,    0,  242,  245,  248,
      249,  242,  247,  258,  249,  243,    0,  251,    0,    0,
      244,  243,  246,  232,  246,  239,  238,  241,  227,  232,
      236,    0,  231,  228,  229,  238,    0,  226,  236,  233,

      119,  218,  227,    0,  220,    0,  225,  224,    0,  213,
        0,  123,  222,  211,  210,    0,  209,  208,  212,  212,
        0,  204,  203,  203,  204,    0,  200,  199,  199,  200,
      203,  201,    0,  209,  208,  193,  194,  205,    0,  195,
      184,  187,  199,  204,  190,  201,  197,  187,  176,  185,
      189,  196,    0,  187,  182,  202,  175,  174,  183,  172,
      171,  170,  179,  168,    0,  172,    0,    0,  175,    0,
        0,  170,  167,  162,  171,  176,  165,  157,  182,  162,
      159,  160,  158,  152,  156,    0,  160,  159,  158,    0,
        0,  157,  156,    0,    0,    0,  150,  144,  157,  152,

      141,  154,    0,  139,  140,  137,  150,  136,  140,  143,
      138,  143,  128,  127,  126,  125,  132,  139,    0,  129,
      124,    0,  136,  126,  134,    0,    0,    0,  124,    0,
      128,  131,  130,  129,  128,    0,  119,  118,    0,    0,
      110,  116,  114,  102,    0,    0,    0,    0,  101,  125,
      102,   97,    0,   97,    0,   88,    0,    0,    0,   74,
       67,   69,    0,  491,  149,  152,   55
    } ;

static yyconst short int yy_def[468] =
    {   0,
      464,    1,  464,  464,  464,  464,  464,  465,  466,  464,
      464,  464,  464,  464,  464,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  465,  464,  465,
      466,  466,  464,  464,  464,  464,  464,  467,  465,  466,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  464,  464,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  464,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,

      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,  467,  467,  467,  467,  467,  467,  467,
      467,  467,  467,    0,  464,  464,  464
    } ;

static yyconst short int yy_nxt[543] =
    {   0,
        4,    5,    6,    7,    4,    8,    9,    4,   10,    4,
       11,   12,   13,   14,   15,   16,   16,   16,   16,   16,
       16,   16,   17,   16,   16,   16,    4,   18,   19,   20,
       21,   22,   23,   24,   16,   25,   26,   27,   28,   29,
       30,   31,   16,   32,   33,   34,   35,   16,   36,   37,
       16,   39,   44,   49,   50,   56,   45,   48,   51,   80,
       59,   61,   46,   57,   81,   52,   60,   53,   58,   54,
       62,   66,   40,   55,   63,   78,   64,   70,   71,   67,
       73,   75,   82,   89,   74,   76,   65,   68,   79,   77,
       85,   92,   86,   90,   94,   83,   87,   39,  464,   96,

       95,   93,   41,   39,  100,  109,  113,   88,  121,  133,
      463,  134,  136,  462,  461,  101,  150,  110,   40,   42,
      122,  151,  114,  139,   40,  206,  137,  207,  140,  141,
      180,  460,  181,  182,  183,  185,  340,  186,  187,  188,
      348,  459,  458,  457,  341,  456,  455,  454,  349,   38,
       38,   38,   41,  453,   41,  452,  451,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  441,  440,  439,  438,
      437,  436,  435,  434,  433,  432,  431,  430,  429,  428,
      427,  426,  425,  424,  423,  422,  421,  420,  419,  418,
      417,  416,  415,  414,  413,  412,  411,  410,  409,  408,

      407,  406,  405,  404,  403,  402,  401,  400,  399,  398,
      397,  396,  395,  394,  393,  392,  391,  390,  389,  388,
      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  347,  346,
      345,  344,  343,  342,  339,  338,  337,  336,  335,  334,
      333,  332,  331,  330,  329,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  311,  310,  309,  308,  307,  306,  305,  304,

      303,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  228,  227,  226,  225,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  205,  204,  203,  202,

      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  184,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  149,  148,  147,  146,  145,  144,  143,  142,
      138,  135,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  120,  119,  118,  117,  116,  115,  112,  111,
      108,  107,  106,  105,  104,  103,  102,   99,   98,   42,
       97,  464,   91,   84,   72,   69,   47,   43,   42,  464,
        3,  464,  464,  464,  464,  464,  464,  464,  464,  464,

      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464
    } ;

static yyconst short int yy_chk[543] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    8,   12,   17,   17,   19,   12,  467,   18,   30,
       20,   21,   12,   19,   30,   18,   20,   18,   19,   18,
       21,   23,    8,   18,   22,   29,   22,   25,   25,   23,
       27,   28,   31,   34,   27,   28,   22,   23,   29,   28,
       33,   36,   33,   34,   37,   31,   33,   38,   42,   41,

       37,   36,   42,   49,   53,   61,   64,   33,   71,   82,
      462,   82,   84,  461,  460,   53,   95,   61,   38,   41,
       71,   95,   64,   86,   49,  146,   84,  146,   86,   86,
      126,  456,  126,  126,  126,  128,  301,  128,  128,  128,
      312,  454,  452,  451,  301,  450,  449,  444,  312,  465,
      465,  465,  466,  443,  466,  442,  441,  438,  437,  435,
      434,  433,  432,  431,  429,  425,  424,  423,  421,  420,
      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  402,  401,  400,  399,  398,
      397,  393,  392,  389,  388,  387,  385,  384,  383,  382,

      381,  380,  379,  378,  377,  376,  375,  374,  373,  372,
      369,  366,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  352,  351,  350,  349,  348,  347,  346,
      345,  344,  343,  342,  341,  340,  338,  337,  336,  335,
      334,  332,  331,  330,  329,  328,  327,  325,  324,  323,
      322,  320,  319,  318,  317,  315,  314,  313,  310,  308,
      307,  305,  303,  302,  300,  299,  298,  296,  295,  294,
      293,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  278,  276,  275,  274,  273,  272,  271,  270,
      269,  268,  266,  265,  264,  263,  262,  261,  260,  259,

      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  230,  229,  227,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  208,  207,  206,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  192,  191,
      190,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  159,  157,
      156,  155,  154,  153,  148,  147,  145,  144,  143,  142,

      141,  140,  139,  138,  137,  136,  135,  134,  133,  132,
      131,  130,  129,  127,  125,  124,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  101,  100,
       98,   97,   94,   93,   92,   91,   90,   89,   88,   87,
       85,   83,   81,   80,   79,   78,   77,   76,   75,   74,
       73,   72,   70,   69,   68,   67,   66,   65,   63,   62,
       60,   59,   58,   57,   56,   55,   54,   52,   51,   50,
       44,   40,   35,   32,   26,   24,   15,   10,    9,    3,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,

      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464,  464,  464,  464,  464,  464,  464,  464,  464,
      464,  464
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "wsdl.lex"
#define INITIAL 0
#line 4 "wsdl.lex"
#include <stdio.h>
#include <string.h>
int main()
{
	  yylex();
}
FILE * kros;
FILE * iden;
FILE * kons;
FILE * unif;
int br=1;

#line 650 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 19 "wsdl.lex"

  		  	{iden = fopen ("iden.txt","w"); fclose(iden); kons = fopen ("kons.txt","w"); fclose(kons); kros = fopen("kros.txt","w"); iden = fopen ("iden.txt","a+"); kons = fopen ("kons.txt","a+"); unif = fopen ("unif.txt","w"); upiskros(kros);}
#line 800 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 465 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 491 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "wsdl.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 23 "wsdl.lex"
{ fprintf(unif,"KROS 1\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 24 "wsdl.lex"
{ fprintf(unif,"KROS 2\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "wsdl.lex"
{ fprintf(unif,"KROS 3\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 26 "wsdl.lex"
{ fprintf(unif,"KROS 4\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 27 "wsdl.lex"
{ fprintf(unif,"KROS 5\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 28 "wsdl.lex"
{ fprintf(unif,"KROS 6\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 29 "wsdl.lex"
{ fprintf(unif,"KROS 7\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "wsdl.lex"
{ fprintf(unif,"KROS 8\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 31 "wsdl.lex"
{ fprintf(unif,"KROS 9\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 32 "wsdl.lex"
{ fprintf(unif,"KROS 10\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 33 "wsdl.lex"
{ fprintf(unif,"KROS 11\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 34 "wsdl.lex"
{ fprintf(unif,"KROS 12\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "wsdl.lex"
{ fprintf(unif,"KROS 13\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "wsdl.lex"
{ fprintf(unif,"KROS 14\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "wsdl.lex"
{ fprintf(unif,"KROS 15\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "wsdl.lex"
{ fprintf(unif,"KROS 16\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "wsdl.lex"
{ fprintf(unif,"KROS 17\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "wsdl.lex"
{ fprintf(unif,"KROS 18\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "wsdl.lex"
{ fprintf(unif,"KROS 19\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "wsdl.lex"
{ fprintf(unif,"KROS 20\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "wsdl.lex"
{ fprintf(unif,"KROS 21\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "wsdl.lex"
{ fprintf(unif,"KROS 22\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "wsdl.lex"
{ fprintf(unif,"KROS 23\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "wsdl.lex"
{ fprintf(unif,"KROS 24\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "wsdl.lex"
{ fprintf(unif,"KROS 25\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 48 "wsdl.lex"
{ fprintf(unif,"KROS 26\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 49 "wsdl.lex"
{ fprintf(unif,"KROS 27\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 50 "wsdl.lex"
{ fprintf(unif,"KROS 28\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 51 "wsdl.lex"
{ fprintf(unif,"KROS 29\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 52 "wsdl.lex"
{ fprintf(unif,"KROS 30\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 53 "wsdl.lex"
{ fprintf(unif,"KROS 31\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 54 "wsdl.lex"
{ fprintf(unif,"KROS 32\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 55 "wsdl.lex"
{ fprintf(unif,"KROS 33\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 56 "wsdl.lex"
{ fprintf(unif,"KROS 34\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 57 "wsdl.lex"
{ fprintf(unif,"KROS 35\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 58 "wsdl.lex"
{ fprintf(unif,"KROS 36\n"); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 59 "wsdl.lex"
{ fprintf(unif,"KROS 37\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "wsdl.lex"
{ fprintf(unif,"KROS 38\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "wsdl.lex"
{ fprintf(unif,"KROS 39\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "wsdl.lex"
{ fprintf(unif,"KROS 40\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 63 "wsdl.lex"
{ fprintf(unif,"KROS 41\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 64 "wsdl.lex"
{ fprintf(unif,"KROS 42\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 65 "wsdl.lex"
{ fprintf(unif,"KROS 43\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 66 "wsdl.lex"
{ fprintf(unif,"KROS 44\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "wsdl.lex"
{ fprintf(unif,"KROS 45\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "wsdl.lex"
{ fprintf(unif,"KROS 46\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "wsdl.lex"
{ fprintf(unif,"KROS 47\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 70 "wsdl.lex"
{ fprintf(unif,"KROS 48\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "wsdl.lex"
{ fprintf(unif,"KROS 49\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 72 "wsdl.lex"
{ fprintf(unif,"KROS 50\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "wsdl.lex"
{ fprintf(unif,"KROS 51\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 74 "wsdl.lex"
{ fprintf(unif,"KROS 52\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 75 "wsdl.lex"
{ fprintf(unif,"KROS 53\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 76 "wsdl.lex"
{ fprintf(unif,"KROS 54\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 77 "wsdl.lex"
{ fprintf(unif,"KROS 55\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 78 "wsdl.lex"
{ fprintf(unif,"KROS 56\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 79 "wsdl.lex"
{ fprintf(unif,"KROS 57\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 80 "wsdl.lex"
{ fprintf(unif,"KROS 58\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 81 "wsdl.lex"
{ fprintf(unif,"KROS 59\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "wsdl.lex"
{ fprintf(unif,"KROS 60\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "wsdl.lex"
{ fprintf(unif,"KROS 61\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "wsdl.lex"
{ fprintf(unif,"KROS 62\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "wsdl.lex"
{ fprintf(unif,"KROS 63\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "wsdl.lex"
{ fprintf(unif,"KROS 64\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "wsdl.lex"
{ fprintf(unif,"KROS 65\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "wsdl.lex"
{ fprintf(unif,"KROS 66\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "wsdl.lex"
{ fprintf(unif,"KROS 67\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "wsdl.lex"
{ fprintf(unif,"KROS 68\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "wsdl.lex"
{ fprintf(unif,"KROS 69\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "wsdl.lex"
{ fprintf(unif,"KROS 70\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "wsdl.lex"
{ fprintf(unif,"KROS 71\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "wsdl.lex"
{ fprintf(unif,"KROS 72\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "wsdl.lex"
{ fprintf(unif,"KROS 73\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "wsdl.lex"
{ fprintf(unif,"KROS 74\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 97 "wsdl.lex"
{ fprintf(unif,"KROS 75\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 98 "wsdl.lex"
{ fprintf(unif,"KROS 76\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 99 "wsdl.lex"
{ fprintf(unif,"KROS 77\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 100 "wsdl.lex"
{ fprintf(unif,"KROS 78\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "wsdl.lex"
{ idn(unif, iden); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 "wsdl.lex"
{ konstanta(unif, kons); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "wsdl.lex"
{ konstanta(unif, kons); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 109 "wsdl.lex"
{ ; /*brisanje praznina*/ }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 110 "wsdl.lex"
{ br++; /*preskakanje novog reda i brojanje zbog javljanja greske*/}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 111 "wsdl.lex"
{ printf("greska(%d): %s\n",br, yytext); /*oporavak od greske*/ }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "wsdl.lex"
ECHO;
	YY_BREAK
#line 1313 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 465 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 465 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 464);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 113 "wsdl.lex"


upiskros(FILE * kros)
{
 fprintf(kros,"description\n");
 fprintf(kros,"service\n");
 fprintf(kros,"endpoint\n");
 fprintf(kros,"binding\n");
 fprintf(kros,"operation\n");
 fprintf(kros,"xml\n");
 fprintf(kros,"schema\n");
 fprintf(kros,"element\n");
 fprintf(kros,"complexType\n");
 fprintf(kros,"choice\n");
 fprintf(kros,"any\n");
 fprintf(kros,"anyAttribute\n");
 fprintf(kros,"sequence\n");
 fprintf(kros,"annotation\n");
 fprintf(kros,"documentation\n");
 fprintf(kros,"key\n");
 fprintf(kros,"selector\n");
 fprintf(kros,"field\n");
 fprintf(kros,"extension\n");
 fprintf(kros,"attribute\n");
 fprintf(kros,"unique\n");
 fprintf(kros,"complexContent\n");
 fprintf(kros,"group\n");
 fprintf(kros,"port\n");
 fprintf(kros,"types\n");
 fprintf(kros,"message\n");
 fprintf(kros,"portType\n");
 fprintf(kros,"simpleType\n");
 fprintf(kros,"enumeration\n");
 fprintf(kros,"restriction\n");
 fprintf(kros,"all\n");
 fprintf(kros,"wsdl\n");
 fprintf(kros,"input\n");
 fprintf(kros,"output\n");
 fprintf(kros,"fault\n");
 fprintf(kros,"part\n");
 fprintf(kros,"definitions\n");
 fprintf(kros,"address\n");
 fprintf(kros,"xsd\n");
 fprintf(kros,"xs\n");
 fprintf(kros,"xsi\n");
 fprintf(kros,"pattern\n");
 fprintf(kros,"whiteSpace\n");
 fprintf(kros,"length\n");
 fprintf(kros,"fractionDigits\n");
 fprintf(kros,"maxExclusive\n");
 fprintf(kros,"maxInclusive\n");
 fprintf(kros,"maxLength\n");
 fprintf(kros,"minExclusive\n");
 fprintf(kros,"minInclusive\n");
 fprintf(kros,"minLength\n");
 fprintf(kros,"totalDigits\n");
 fprintf(kros,"simpleContent\n");
 fprintf(kros,"maxOccurs\n");
 fprintf(kros,"minOccurs\n");
 fprintf(kros,"name\n");
 fprintf(kros,"attributeGroup\n");
 fprintf(kros,"substitutionGroup\n");
 fprintf(kros,"base\n");
 fprintf(kros,"appInfo\n");
 fprintf(kros,"import\n");
 fprintf(kros,"include\n");
 fprintf(kros,"keyref\n");
 fprintf(kros,"list\n");
 fprintf(kros,"notation\n");
 fprintf(kros,"redifine\n");
 fprintf(kros,"union\n");
 fprintf(kros,"body\n");
 fprintf(kros,"type\n");
 fprintf(kros,"</\n");
 fprintf(kros,"<?\n");
 fprintf(kros,"<\n");
 fprintf(kros,"=\n");
 fprintf(kros,"/>\n");
 fprintf(kros,"?>\n");
 fprintf(kros,">\n");
 fprintf(kros,":\n");
 fprintf(kros,"/\n");
}

idn(FILE * unif, FILE * iden)
{
	 char tmp[50];
	 int flag = 0;
	 int count = 1;
	 rewind(iden);
	 while(fgets(tmp,49,iden)!=NULL)
	 {
		tmp[strlen(tmp)-1]='\0';
		if (strcmp(tmp,yytext)==0) flag=1;
		if (flag==0) count++;
	 }
	 if (flag==0) fprintf(iden,"%s\n",yytext);
	 fprintf(unif, "IDN %d\n", count);
}

konstanta(FILE * unif, FILE * kons)
{
	 char tmp[50];
	 int flag = 0;
	 int count = 1;
	 rewind(kons);
	 while(fgets(tmp,49,kons)!=NULL)
	 {
		tmp[strlen(tmp)-1]='\0';
		if (strcmp(tmp,yytext)==0) flag=1;
		if (flag==0) count++;
	 }
	 if (flag==0) fprintf(kons,"%s\n",yytext);
	 fprintf(unif, "KON %d\n", count);
}


comment()
{
	char c, c1, c2;
loop:
	while ((c = input()) != '-' && c != 0)
		//putchar(c);
	c1 = input();
	c2 = input();
	if (((c != '-') || (c1 != '-') || (c2 != '>')) && (c != 0))
	{
		unput(c2);
		unput(c1);
		//putchar(c);
		goto loop;
	}	
}

