
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 34
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 * Given that the standard has decreed that size_t exists since 1989,
 * I guess we can afford to depend on it. Manoj.
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 158
#define YY_END_OF_BUFFER 159
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[597] =
    {   0,
        0,    0,  159,  158,  151,  148,  151,  158,  145,  146,
      138,  136,  147,  137,  150,  139,  155,  149,  144,  140,
      134,  141,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  142,  143,  151,  135,    0,  151,  151,
      153,    0,  154,  155,  132,  133,  157,  157,  157,  157,
      157,    2,  157,  157,    4,  157,  157,  157,  157,  157,
        8,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   22,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   28,  157,  157,  157,  157,  157,

      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   36,  157,  157,  157,  157,  157,
      157,  157,  156,    0,  154,    0,  157,    1,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
       57,  157,  157,   13,  157,  157,  157,  157,  157,  157,
      157,   18,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   74,  157,  157,  157,  157,   27,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  111,  157,  157,  157,  157,  157,  157,  117,

      157,  157,  157,  157,  157,  157,  157,  157,  157,   42,
      152,    0,    0,  154,  157,  157,  157,  157,   47,  157,
      157,  157,   50,    5,  157,  157,  157,  157,  157,  157,
       58,    9,  157,  157,   15,  157,   16,  157,   60,  157,
      157,  157,   65,  157,   67,  157,   21,   68,   69,  157,
      157,  157,  157,  157,  157,   26,  157,  157,  157,  157,
      157,   83,  157,  157,  157,   86,  157,  157,   94,  157,
      157,  157,  157,  157,  157,  157,  103,  104,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  114,  157,
      157,  118,  157,   35,  128,  157,   37,  157,  157,  157,

       40,  157,   43,  157,  157,  157,    3,  157,  157,  157,
      157,   54,  157,  157,  157,  157,  157,   11,   14,   59,
      157,  157,   62,  157,  157,  157,  157,  157,   23,  157,
      157,  157,   25,  157,  157,   77,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,   92,  157,   95,
       96,  157,   98,  157,  100,  157,  157,  157,  157,  157,
      157,  157,   32,  157,  157,  157,  157,  157,  157,  157,
      157,  129,   38,  157,   39,  157,  157,  157,   45,   46,
       48,   49,  157,  157,  157,  157,  157,  157,  157,  157,
      157,   17,  157,  157,  157,  157,   66,   20,  157,   71,

      157,   73,  157,  157,  157,  157,  157,   82,  157,  157,
      157,   88,   89,   90,   91,  157,  157,  157,  157,  101,
      157,  157,   31,  157,  106,  107,  157,   33,  157,  157,
      112,  157,   34,  115,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,   56,  157,  157,   10,
      157,  157,  157,   63,  157,   24,   72,  157,  157,  157,
       80,  157,  157,   85,  157,  157,  157,  157,   99,  157,
      102,  157,  108,  157,  157,  113,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  130,   41,  157,   44,  157,
      157,  157,  157,    6,    7,   12,  157,   19,  157,  157,

      157,  157,   79,   81,  157,   29,  157,   93,   97,  157,
      157,  157,  110,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  131,   51,   52,  157,  157,   61,   64,  157,
      157,  157,  157,  157,  157,   30,  105,  157,  157,  157,
      157,  122,  157,  124,  157,  157,  157,  157,  157,  157,
      157,  157,   78,  157,   87,  109,  157,  157,  157,  157,
      157,  157,  127,  157,  157,  157,  157,  157,  157,  116,
      157,  121,  157,  125,  157,   53,   55,  157,   75,   76,
      157,  157,  157,  126,   70,  157,  157,  123,  157,  157,
      157,   84,  157,  120,  119,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    1,    1,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   16,   17,
       18,   19,   16,   16,   16,   16,   16,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
        1,    1,    1,    1,   28,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   27,   54,    1,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    5,    5,    5,    5,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1
    } ;

static yyconst flex_int16_t yy_base[601] =
    {   0,
        0,    0,  676,  677,   54,  652,   59,   50,  677,  677,
      677,  677,  677,  661,  677,  677,   63,  677,  677,  650,
      677,  649,    0,   41,   38,   64,   30,   54,   60,   62,
       41,   30,   79,   57,  628,   71,   83,   81,   94,   82,
      628,  104,  626,  677,  677,  140,  677,  131,  146,  151,
      142,  655,  146,  157,  677,  677,    0,  624,  634,  621,
      633,    0,  620,  629,    0,  122,  130,  136,  139,  613,
        0,  613,  146,  610,  145,  616,  614,  610,  613,  606,
      610,  604,  604,  621,  617,  152,  618,  605,  149,   82,
      605,  597,  606,  103,  615,  609,  608,  588,  610,  146,

      165,  157,  596,  162,  588,  591,  593,  150,  588,  596,
      585,  167,  598,  589,    0,  600,  584,  579,  580,  588,
      576,  577,  677,  619,  199,  210,  575,  592,  586,  570,
      576,  587,  566,  568,  573,  579,  582,  563,  147,  164,
        0,  576,  187,    0,  562,  566,  577,  557,  561,  571,
      559,    0,  570,  202,  570,  556,  562,  565,  563,  555,
      561,  560,  559,  556,    0,  546,  553,  557,  559,  558,
      552,  542,  546,  552,  535,  541,  546,  530,  544,  539,
      542,  530,  531,  188,  532,  524,  538,  202,  199,  188,
      521,  519,    0,  530,  529,  517,  516,  515,  522,    0,

      522,  518,  526,  527,  524,  519,  513,  514,  517,  524,
      677,  548,  224,  234,  502,  519,  506,  518,    0,  507,
      503,  501,  515,    0,  496,  508,  511,  510,  490,  500,
        0,  504,  501,  481,    0,  493,    0,  486,  503,  484,
      481,  215,    0,  486,    0,  498,    0,    0,    0,  492,
      476,  478,  488,  482,  473,    0,  483,  483,  213,  488,
      486,    0,  473,  478,  468,  229,  473,  478,  219,  463,
      464,  476,  460,  474,  469,  468,    0,    0,  467,  453,
      473,  472,  447,  453,  461,  464,  465,  453,    0,  463,
      460,    0,  464,    0,    0,  458,    0,  450,  452,  455,

      444,  456,    0,  448,  452,  441,    0,  451,  450,  221,
      452,    0,  437,  432,  448,  434,  442,  442,    0,    0,
      425,  438,    0,  434,  437,  432,  418,  427,    0,  434,
      417,  431,    0,  427,  420,  433,  417,  426,  421,  409,
      414,  407,  417,  406,  403,  209,  404,    0,  407,    0,
        0,  412,    0,  406,  413,  414,  405,  413,  401,  409,
      393,  409,    0,  397,  396,  395,  403,  387,  398,  392,
      230,    0,    0,  390,    0,  382,  393,  381,    0,    0,
        0,    0,  379,  381,  379,  393,  391,  381,  373,  387,
      387,    0,  373,  375,  364,  364,    0,    0,  382,    0,

      368,    0,  380,  378,  367,  362,  361,    0,  380,  360,
      374,    0,    0,    0,    0,  357,  358,  360,  370,    0,
      352,  367,    0,  367,    0,    0,  365,    0,  364,  365,
        0,  361,    0,  366,  161,  356,  231,  355,  356,  342,
      341,  341,  345,  343,  354,  356,    0,  335,  349,    0,
      347,  337,  337,    0,  345,  349,    0,  348,  329,  321,
        0,  326,  325,    0,  338,  333,  328,  326,    0,  321,
        0,  333,    0,  337,  331,    0,  330,  319,  328,  313,
      323,  318,  328,  309,  322,    0,    0,  307,    0,  322,
      321,  305,  310,    0,    0,    0,  308,    0,  308,  303,

      229,  303,    0,    0,  294,    0,  302,    0,    0,  310,
      296,  304,    0,  288,  308,  309,  289,  303,  301,  286,
      289,  292,    0,    0,    0,  298,  293,    0,    0,  300,
      279,  281,  285,  288,  289,    0,    0,  291,  289,  282,
      272,    0,  287,    0,  269,  284,  284,  282,  272,  265,
      270,  268,    0,  262,    0,    0,  278,  280,  274,  257,
      258,  262,    0,  261,  269,  265,  267,  263,  251,    0,
      231,    0,  236,    0,  243,    0,    0,  227,    0,    0,
      236,  223,  236,    0,    0,  235,  238,    0,  219,  167,
       54,    0,   30,    0,    0,  677,  283,  285,  289,  294

    } ;

static yyconst flex_int16_t yy_def[601] =
    {   0,
      596,    1,  596,  596,  596,  596,  597,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  596,  596,  596,  596,  597,  597,  596,
      596,  599,  596,  596,  596,  596,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  596,  600,  596,  596,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      596,  600,  596,  596,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,

      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,  598,  598,  598,  598,  598,
      598,  598,  598,  598,  598,    0,  596,  596,  596,  596

    } ;

static yyconst flex_int16_t yy_nxt[733] =
    {   0,
        4,    5,    5,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   17,   17,   17,   18,
       19,   20,   21,   22,   23,   23,   23,    4,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   23,   23,   33,
       34,   35,   36,   37,   23,   38,   39,   40,   41,   23,
       42,   43,   23,   44,   45,   46,   46,   46,   70,   46,
       49,   46,   49,   85,   50,   51,   51,   51,   51,   83,
       58,   86,   71,   84,   51,   51,   53,  595,   54,   54,
       54,   54,   59,   64,   60,   90,   61,   62,   63,   91,
       65,   66,   67,   72,   80,   73,   76,  594,   74,   77,

       93,   81,   78,   68,   82,   75,   69,   87,   79,  103,
      112,   88,  167,  104,   94,   97,   95,  113,  114,   98,
       96,   89,   99,  105,  115,  100,  106,  116,  101,  168,
      107,  102,  119,  596,  117,  172,  123,  108,  109,  120,
      121,   46,   46,   46,  110,   46,  111,   49,   46,   49,
      173,   50,   46,   46,   46,  133,   46,   51,   51,   51,
       51,  125,  125,  125,  125,  134,   51,   51,  137,  135,
       53,  126,   54,   54,   54,   54,  136,  144,  138,  139,
      140,  148,  160,  165,  179,  141,  185,  227,  149,  194,
      228,  166,  180,  145,  146,  195,  181,  182,  161,  162,

      478,  183,  188,  199,  186,  189,  479,  184,  200,  190,
      229,  230,  593,  201,  125,  125,  125,  125,  274,  232,
      213,  275,  213,  233,  126,  214,  214,  214,  214,  242,
      279,  281,  243,  283,  244,  350,  284,  351,  282,  214,
      214,  214,  214,  337,  280,  344,  345,  346,  245,  214,
      214,  214,  214,  325,  383,  414,  347,  415,  326,  338,
      435,  481,  531,  482,  384,  592,  590,  589,  588,  436,
      587,  586,  532,  585,  584,  583,  437,  582,  483,  484,
      591,  581,  438,   48,   48,   48,   48,   48,   48,   57,
       57,  124,  124,  580,  124,  212,  212,  579,  212,  212,

      578,  577,  576,  575,  574,  573,  572,  571,  570,  569,
      568,  567,  566,  565,  564,  563,  562,  561,  560,  559,
      558,  557,  556,  555,  554,  553,  552,  551,  550,  549,
      548,  547,  546,  545,  544,  543,  542,  541,  540,  539,
      538,  537,  536,  535,  534,  533,  530,  529,  528,  527,
      526,  525,  524,  523,  522,  521,  520,  519,  518,  517,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,
      506,  505,  504,  503,  502,  501,  500,  499,  498,  497,
      496,  495,  494,  493,  492,  491,  490,  489,  488,  487,
      486,  485,  480,  477,  476,  475,  474,  473,  472,  471,

      470,  469,  468,  467,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  452,  451,
      450,  449,  448,  447,  446,  445,  444,  443,  442,  441,
      440,  439,  434,  433,  432,  431,  430,  429,  428,  427,
      426,  425,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  413,  412,  411,  410,  409,  408,  407,  406,  405,
      404,  403,  402,  401,  400,  399,  398,  397,  396,  395,
      394,  393,  392,  391,  390,  389,  388,  387,  386,  385,
      382,  381,  380,  379,  378,  377,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,

      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  349,  348,  343,  342,  341,  340,  339,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  324,  323,
      322,  321,  320,  319,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      211,  302,  301,  300,  299,  298,  297,  296,  295,  294,
      293,  292,  291,  290,  289,  288,  287,  286,  285,  278,
      277,  276,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  252,  251,  250,  249,  248,  247,  246,

      241,  240,  239,  238,  237,  236,  235,  234,  231,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  198,  197,  196,  193,  192,  191,  187,  178,  177,
      176,  175,  174,  171,  170,  169,  164,  163,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  147,  143,
      142,  132,  131,  130,  129,  128,  127,   52,  122,  118,
       92,   56,   55,   52,   47,  596,    3,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static yyconst flex_int16_t yy_chk[733] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    5,   27,    5,
        7,    7,    7,   32,    7,    8,    8,    8,    8,   31,
       24,   32,   27,   31,    8,    8,   17,  593,   17,   17,
       17,   17,   24,   25,   24,   34,   24,   24,   24,   34,
       25,   26,   26,   28,   30,   28,   29,  591,   28,   29,

       36,   30,   29,   26,   30,   28,   26,   33,   29,   38,
       40,   33,   90,   38,   36,   37,   36,   40,   40,   37,
       36,   33,   37,   38,   40,   37,   39,   40,   37,   90,
       39,   37,   42,   48,   40,   94,   48,   39,   39,   42,
       42,   46,   46,   46,   39,   46,   39,   49,   49,   49,
       94,   49,   50,   50,   50,   66,   50,   51,   51,   51,
       51,   53,   53,   53,   53,   66,   51,   51,   68,   67,
       54,   53,   54,   54,   54,   54,   67,   73,   68,   69,
       69,   75,   86,   89,  100,   69,  102,  139,   75,  108,
      139,   89,  100,   73,   73,  108,  100,  101,   86,   86,

      435,  101,  104,  112,  102,  104,  435,  101,  112,  104,
      140,  140,  590,  112,  125,  125,  125,  125,  184,  143,
      126,  184,  126,  143,  125,  126,  126,  126,  126,  154,
      188,  189,  154,  190,  154,  269,  190,  269,  189,  213,
      213,  213,  213,  259,  188,  266,  266,  266,  154,  214,
      214,  214,  214,  242,  310,  346,  266,  346,  242,  259,
      371,  437,  501,  437,  310,  589,  587,  586,  583,  371,
      582,  581,  501,  578,  575,  573,  371,  571,  437,  437,
      587,  569,  371,  597,  597,  597,  597,  597,  597,  598,
      598,  599,  599,  568,  599,  600,  600,  567,  600,  600,

      566,  565,  564,  562,  561,  560,  559,  558,  557,  554,
      552,  551,  550,  549,  548,  547,  546,  545,  543,  541,
      540,  539,  538,  535,  534,  533,  532,  531,  530,  527,
      526,  522,  521,  520,  519,  518,  517,  516,  515,  514,
      512,  511,  510,  507,  505,  502,  500,  499,  497,  493,
      492,  491,  490,  488,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  475,  474,  472,  470,  468,  467,  466,
      465,  463,  462,  460,  459,  458,  456,  455,  453,  452,
      451,  449,  448,  446,  445,  444,  443,  442,  441,  440,
      439,  438,  436,  434,  432,  430,  429,  427,  424,  422,

      421,  419,  418,  417,  416,  411,  410,  409,  407,  406,
      405,  404,  403,  401,  399,  396,  395,  394,  393,  391,
      390,  389,  388,  387,  386,  385,  384,  383,  378,  377,
      376,  374,  370,  369,  368,  367,  366,  365,  364,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  352,  349,
      347,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  332,  331,  330,  328,  327,  326,  325,
      324,  322,  321,  318,  317,  316,  315,  314,  313,  311,
      309,  308,  306,  305,  304,  302,  301,  300,  299,  298,
      296,  293,  291,  290,  288,  287,  286,  285,  284,  283,

      282,  281,  280,  279,  276,  275,  274,  273,  272,  271,
      270,  268,  267,  265,  264,  263,  261,  260,  258,  257,
      255,  254,  253,  252,  251,  250,  246,  244,  241,  240,
      239,  238,  236,  234,  233,  232,  230,  229,  228,  227,
      226,  225,  223,  222,  221,  220,  218,  217,  216,  215,
      212,  210,  209,  208,  207,  206,  205,  204,  203,  202,
      201,  199,  198,  197,  196,  195,  194,  192,  191,  187,
      186,  185,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,

      153,  151,  150,  149,  148,  147,  146,  145,  142,  138,
      137,  136,  135,  134,  133,  132,  131,  130,  129,  128,
      127,  124,  122,  121,  120,  119,  118,  117,  116,  114,
      113,  111,  110,  109,  107,  106,  105,  103,   99,   98,
       97,   96,   95,   93,   92,   91,   88,   87,   85,   84,
       83,   82,   81,   80,   79,   78,   77,   76,   74,   72,
       70,   64,   63,   61,   60,   59,   58,   52,   43,   41,
       35,   22,   20,   14,    6,    3,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,

      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596,  596,  596,  596,  596,  596,  596,  596,  596,
      596,  596
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "euphoria.l"
#line 10 "euphoria.l"
int brKROS=1;
int brKON=1;
int brIDN=1;

void dodaj(char *tip, int br);
void dodajKROS(char *s);
void dodajIDN(char *s);
void dodajKON(char *s);
void pretraziKROS(char *s);
void pretraziIDN(char *s);



int yywrap(void){
  return 1;
}
int main(int argc, char *argv[])
{
if((yyin=fopen(argv[1],"r"))==NULL) {
printf("Nemogu otvoriti ulaznu datoteku.\n");
exit(1);}
yylex();
fclose(yyin);
return 0;
}

#line 843 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 39 "euphoria.l"


#line 999 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 597 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 677 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
#line 42 "euphoria.l"
case 2:
#line 43 "euphoria.l"
case 3:
#line 44 "euphoria.l"
case 4:
#line 45 "euphoria.l"
case 5:
#line 46 "euphoria.l"
case 6:
#line 47 "euphoria.l"
case 7:
#line 48 "euphoria.l"
case 8:
#line 49 "euphoria.l"
case 9:
#line 50 "euphoria.l"
case 10:
#line 51 "euphoria.l"
case 11:
#line 52 "euphoria.l"
case 12:
#line 53 "euphoria.l"
case 13:
#line 54 "euphoria.l"
case 14:
#line 55 "euphoria.l"
case 15:
#line 56 "euphoria.l"
case 16:
#line 57 "euphoria.l"
case 17:
#line 58 "euphoria.l"
case 18:
#line 59 "euphoria.l"
case 19:
#line 60 "euphoria.l"
case 20:
#line 61 "euphoria.l"
case 21:
#line 62 "euphoria.l"
case 22:
#line 63 "euphoria.l"
case 23:
#line 64 "euphoria.l"
case 24:
#line 65 "euphoria.l"
case 25:
#line 66 "euphoria.l"
case 26:
#line 67 "euphoria.l"
case 27:
#line 68 "euphoria.l"
case 28:
#line 69 "euphoria.l"
case 29:
#line 70 "euphoria.l"
case 30:
#line 71 "euphoria.l"
case 31:
#line 72 "euphoria.l"
case 32:
#line 73 "euphoria.l"
case 33:
#line 74 "euphoria.l"
case 34:
#line 75 "euphoria.l"
case 35:
#line 76 "euphoria.l"
case 36:
#line 77 "euphoria.l"
case 37:
#line 78 "euphoria.l"
case 38:
#line 79 "euphoria.l"
case 39:
#line 80 "euphoria.l"
case 40:
#line 81 "euphoria.l"
case 41:
#line 82 "euphoria.l"
case 42:
#line 83 "euphoria.l"
case 43:
#line 84 "euphoria.l"
case 44:
#line 85 "euphoria.l"
case 45:
#line 86 "euphoria.l"
case 46:
#line 87 "euphoria.l"
case 47:
#line 88 "euphoria.l"
case 48:
#line 89 "euphoria.l"
case 49:
#line 90 "euphoria.l"
case 50:
#line 91 "euphoria.l"
case 51:
#line 92 "euphoria.l"
case 52:
#line 93 "euphoria.l"
case 53:
#line 94 "euphoria.l"
case 54:
#line 95 "euphoria.l"
case 55:
#line 96 "euphoria.l"
case 56:
#line 97 "euphoria.l"
case 57:
#line 98 "euphoria.l"
case 58:
#line 99 "euphoria.l"
case 59:
#line 100 "euphoria.l"
case 60:
#line 101 "euphoria.l"
case 61:
#line 102 "euphoria.l"
case 62:
#line 103 "euphoria.l"
case 63:
#line 104 "euphoria.l"
case 64:
#line 105 "euphoria.l"
case 65:
#line 106 "euphoria.l"
case 66:
#line 107 "euphoria.l"
case 67:
#line 108 "euphoria.l"
case 68:
#line 109 "euphoria.l"
case 69:
#line 110 "euphoria.l"
case 70:
#line 111 "euphoria.l"
case 71:
#line 112 "euphoria.l"
case 72:
#line 113 "euphoria.l"
case 73:
#line 114 "euphoria.l"
case 74:
#line 115 "euphoria.l"
case 75:
#line 116 "euphoria.l"
case 76:
#line 117 "euphoria.l"
case 77:
#line 118 "euphoria.l"
case 78:
#line 119 "euphoria.l"
case 79:
#line 120 "euphoria.l"
case 80:
#line 121 "euphoria.l"
case 81:
#line 122 "euphoria.l"
case 82:
#line 123 "euphoria.l"
case 83:
#line 124 "euphoria.l"
case 84:
#line 125 "euphoria.l"
case 85:
#line 126 "euphoria.l"
case 86:
#line 127 "euphoria.l"
case 87:
#line 128 "euphoria.l"
case 88:
#line 129 "euphoria.l"
case 89:
#line 130 "euphoria.l"
case 90:
#line 131 "euphoria.l"
case 91:
#line 132 "euphoria.l"
case 92:
#line 133 "euphoria.l"
case 93:
#line 134 "euphoria.l"
case 94:
#line 135 "euphoria.l"
case 95:
#line 136 "euphoria.l"
case 96:
#line 137 "euphoria.l"
case 97:
#line 138 "euphoria.l"
case 98:
#line 139 "euphoria.l"
case 99:
#line 140 "euphoria.l"
case 100:
#line 141 "euphoria.l"
case 101:
#line 142 "euphoria.l"
case 102:
#line 143 "euphoria.l"
case 103:
#line 144 "euphoria.l"
case 104:
#line 145 "euphoria.l"
case 105:
#line 146 "euphoria.l"
case 106:
#line 147 "euphoria.l"
case 107:
#line 148 "euphoria.l"
case 108:
#line 149 "euphoria.l"
case 109:
#line 150 "euphoria.l"
case 110:
#line 151 "euphoria.l"
case 111:
#line 152 "euphoria.l"
case 112:
#line 153 "euphoria.l"
case 113:
#line 154 "euphoria.l"
case 114:
#line 155 "euphoria.l"
case 115:
#line 156 "euphoria.l"
case 116:
#line 157 "euphoria.l"
case 117:
#line 158 "euphoria.l"
case 118:
#line 159 "euphoria.l"
case 119:
#line 160 "euphoria.l"
case 120:
#line 161 "euphoria.l"
case 121:
#line 162 "euphoria.l"
case 122:
#line 163 "euphoria.l"
case 123:
#line 164 "euphoria.l"
case 124:
#line 165 "euphoria.l"
case 125:
#line 166 "euphoria.l"
case 126:
#line 167 "euphoria.l"
case 127:
#line 168 "euphoria.l"
case 128:
#line 169 "euphoria.l"
case 129:
#line 170 "euphoria.l"
case 130:
#line 171 "euphoria.l"
case 131:
#line 172 "euphoria.l"
case 132:
#line 173 "euphoria.l"
case 133:
#line 174 "euphoria.l"
case 134:
#line 175 "euphoria.l"
case 135:
#line 176 "euphoria.l"
case 136:
#line 177 "euphoria.l"
case 137:
#line 178 "euphoria.l"
case 138:
#line 179 "euphoria.l"
case 139:
#line 180 "euphoria.l"
case 140:
#line 181 "euphoria.l"
case 141:
#line 182 "euphoria.l"
case 142:
#line 183 "euphoria.l"
case 143:
#line 184 "euphoria.l"
case 144:
#line 185 "euphoria.l"
case 145:
#line 186 "euphoria.l"
case 146:
#line 187 "euphoria.l"
case 147:
#line 188 "euphoria.l"
case 148:
#line 189 "euphoria.l"
case 149:
#line 190 "euphoria.l"
case 150:
YY_RULE_SETUP
#line 190 "euphoria.l"
pretraziKROS(yytext);   
	YY_BREAK
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 193 "euphoria.l"
{; }
	YY_BREAK
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
#line 194 "euphoria.l"
{; }
	YY_BREAK
case 153:
#line 196 "euphoria.l"
case 154:
#line 197 "euphoria.l"
case 155:
#line 198 "euphoria.l"
case 156:
YY_RULE_SETUP
#line 198 "euphoria.l"
{dodaj("KON   ",brKON++);dodajKON(yytext);}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 199 "euphoria.l"
pretraziIDN(yytext);
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 200 "euphoria.l"
ECHO;
	YY_BREAK
#line 1418 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 597 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 597 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 596);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "euphoria.l"



void pretraziKROS(char *s){
 int x;
 char pom[20];
 int flag=0;
FILE *dat;
dat=fopen("tablicaKROS.txt","r");
if(dat!=NULL)
{
while (fscanf(dat,"%d %s\n",&x,&pom)!=EOF){
 if(strcmp(s,pom)==0){
   flag=1;
   break;}}

fclose(dat);}

if (flag==1) {dodaj("KROS   ",x); }

else {dodaj("KROS   ",brKROS++);dodajKROS(yytext);}

}

void pretraziIDN(char *s){
 int x;
 char pom[100];
 int flag=0;
FILE *dat;
dat=fopen("tablicaIDN.txt","r");
if(dat!=NULL)
{
while (fscanf(dat,"%d %s\n",&x,&pom)!=EOF){
 if(strcmp(s,pom)==0){
   flag=1;
   break;}}

fclose(dat);}

if (flag==1) {dodaj("IDN   ",x); }

else {dodaj("IDN   ",brIDN++);dodajIDN(yytext);}

}






void dodaj(char *tip, int br)
{
FILE *dat;

dat=fopen("izlaz.txt","a");
fputs(tip,dat);
fprintf (dat, "%d\n", br);

fclose(dat);

}


void dodajIDN(char *s)
{
FILE *dat;
char *pom="\n";
dat=fopen("tablicaIDN.txt","a");
fprintf (dat, "%d   ", brIDN-1);
fputs(s,dat);
fputs(pom,dat);
fclose(dat);

}

void dodajKON(char *s)
{
FILE *dat;
char *pom="\n";
dat=fopen("tablicaKON.txt","a");
fprintf (dat, "%d   ", brKON-1);
fputs(s,dat);
fputs(pom,dat);
fclose(dat);

}

void dodajKROS(char *s)
{
FILE *dat;
char *pom="\n";
dat=fopen("tablicaKROS.txt","a");
fprintf (dat, "%d   ", brKROS-1);
fputs(s,dat);
fputs(pom,dat);
fclose(dat);

}









